<?php

namespace AppBundle\Repository;

/**
 * BateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BateriaRepository extends \Doctrine\ORM\EntityRepository
{
}
