<?php

namespace AppBundle\Repository;

/**
 * CentroAlmacenamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroAlmacenamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
