# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('energia', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('energia', models.IntegerField(default=0)),
                ('codigo', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.CharField(max_length=200)),
                ('deshabilitado', models.CharField(max_length=200)),
                ('en_reparacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('bateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Bateria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.EstadoTerminal')),
            ],
        ),
        migrations.AddField(
            model_name='bateria',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Centro'),
        ),
    ]
