# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bateria',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Bateria',
        ),
        migrations.DeleteModel(
            name='Centro',
        ),
        migrations.DeleteModel(
            name='EstadoTerminal',
        ),
        migrations.DeleteModel(
            name='Terminal',
        ),
    ]
