# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('energia', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Centro')),
            ],
        ),
    ]
