# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.CharField(max_length=200)),
                ('deshabilitado', models.CharField(max_length=200)),
                ('en_reparacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('codigo', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('bateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bateria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EstadoTerminal')),
            ],
        ),
    ]
