# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160623_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='bateria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
